In [2]:
import pandas as pd
import numpy as np

In [3]:
originalFile=pd.read_excel("nutrition.xlsx",header=3)

In [4]:
columns=originalFile.columns
columns

Index(['ID', 'name', 'Food Group', 'Calories', 'Fat (g)', 'Protein (g)',
       'Carbohydrate (g)', 'Sugars (g)', 'Fiber (g)', 'Cholesterol (mg)',
       ...
       'Serving Description 5 (g)', 'Serving Weight 6 (g)',
       'Serving Description 6 (g)', 'Serving Weight 7 (g)',
       'Serving Description 7 (g)', 'Serving Weight 8 (g)',
       'Serving Description 8 (g)', 'Serving Weight 9 (g)',
       'Serving Description 9 (g)', '200 Calorie Weight (g)'],
      dtype='object', length=117)

In [5]:
len(columns)

117

In [6]:
oFood=pd.read_csv("food.csv")

In [7]:
columns=oFood.columns
print(columns)
print("columns:",len(columns))

Index(['Category', 'Description', 'Nutrient Data Bank Number',
       'Data.Alpha Carotene', 'Data.Ash', 'Data.Beta Carotene',
       'Data.Beta Cryptoxanthin', 'Data.Carbohydrate', 'Data.Cholesterol',
       'Data.Choline', 'Data.Fiber', 'Data.Kilocalories',
       'Data.Lutein and Zeaxanthin', 'Data.Lycopene', 'Data.Manganese',
       'Data.Niacin', 'Data.Pantothenic Acid', 'Data.Protein',
       'Data.Refuse Percentage', 'Data.Retinol', 'Data.Riboflavin',
       'Data.Selenium', 'Data.Sugar Total', 'Data.Thiamin', 'Data.Water',
       'Data.Fat.Monosaturated Fat', 'Data.Fat.Polysaturated Fat',
       'Data.Fat.Saturated Fat', 'Data.Fat.Total Lipid',
       'Data.Household Weights.1st Household Weight',
       'Data.Household Weights.1st Household Weight Description',
       'Data.Household Weights.2nd Household Weight',
       'Data.Household Weights.2nd Household Weight Description',
       'Data.Major Minerals.Calcium', 'Data.Major Minerals.Copper',
       'Data.Major Minerals.Iron', 'Data.Major Minerals.Magnesium',
       'Data.Major Minerals.Phosphorus', 'Data.Major Minerals.Potassium',
       'Data.Major Minerals.Sodium', 'Data.Major Minerals.Zinc',
       'Data.Vitamins.Vitamin A - IU', 'Data.Vitamins.Vitamin A - RAE',
       'Data.Vitamins.Vitamin B12', 'Data.Vitamins.Vitamin B6',
       'Data.Vitamins.Vitamin C', 'Data.Vitamins.Vitamin E',
       'Data.Vitamins.Vitamin K'],
      dtype='object')
columns: 48

In [10]:
#removing column Data.
new_columns=[]
for i in range(len(columns)):
    new_columns.append(columns[i].replace("ata.",""))
columns=[]
columns=new_columns.copy()
#removing column Vitamins.
new_columns=[]
for i in range(len(columns)):
    new_columns.append(columns[i].replace("vitamins.",""))
#removing column Vitamins.
columns=new_columns.copy()
new_columns=[]
columns
#removing column Fats.
new_columns=[]
for i in range(len(columns)):
    new_columns.append(columns[i].replace("fat.",""))
#removing column Fat
columns=new_columns.copy()
new_columns=[]

#removing column Mineral.
new_columns=[]
for i in range(len(columns)):
    new_columns.append(columns[i].replace("minerals.",""))
#removing column Fat
columns=new_columns.copy()
new_columns=[]
columns
#removing column majors
new_columns=[]
for i in range(len(columns)):
    new_columns.append(columns[i].replace("major ",""))
#removing column Fat
columns=new_columns.copy()
new_columns=[]
columns
#removing column space
for i in range(len(columns)):
    new_columns.append(columns[i].replace(" ",""))
#removing column Fat
columns=new_columns.copy()
new_columns=[]
columns
# def removeColumns(data,From,To):
#     new_columns=[]
#     for i in range(len(data)):
#         new_columns.append(data[i].replace(From,To))
#         return new_columns
# toBeRemoved=["Data.","Vitamins.","Fat.","Minerals.","Major "," "]
# for remove in toBeRemoved:
#     columns=removeColumns(columns,remove,"")
# columns

['Category',
 'Description',
 'NutrientDataBankNumber',
 'AlphaCarotene',
 'Ash',
 'BetaCarotene',
 'BetaCryptoxanthin',
 'Carbohydrate',
 'Cholesterol',
 'Choline',
 'Fiber',
 'Kilocalories',
 'LuteinandZeaxanthin',
 'Lycopene',
 'Manganese',
 'Niacin',
 'PantothenicAcid',
 'Protein',
 'RefusePercentage',
 'Retinol',
 'Riboflavin',
 'Selenium',
 'SugarTotal',
 'Thiamin',
 'Water',
 'MonosaturatedFat',
 'PolysaturatedFat',
 'SaturatedFat',
 'TotalLipid',
 'HouseholdWeights.1stHouseholdWeight',
 'HouseholdWeights.1stHouseholdWeightDescription',
 'HouseholdWeights.2ndHouseholdWeight',
 'HouseholdWeights.2ndHouseholdWeightDescription',
 'Calcium',
 'Copper',
 'Iron',
 'Magnesium',
 'Phosphorus',
 'Potassium',
 'Sodium',
 'Zinc',
 'VitaminA-IU',
 'VitaminA-RAE',
 'VitaminB12',
 'VitaminB6',
 'VitaminC',
 'VitaminE',
 'VitaminK']

In [536]:
oFood=pd.read_csv("food.csv",names=columns)

In [537]:
oFood=pd.read_csv("food.csv",header=0,names=columns)
oFood

,Category,Description,NutrientDataBankNumber,AlphaCarotene,Ash,BetaCarotene,BetaCryptoxanthin,Carbohydrate,Cholesterol,Choline,...,Potassium,Sodium,Zinc,VitaminA-IU,VitaminA-RAE,VitaminB12,VitaminB6,VitaminC,VitaminE,VitaminK
0,BUTTER,"BUTTER,WITH SALT",1001,0,2.11,158,0,0.06,215,19,...,24,576,0.09,2499,684,0.17,0.003,0.0,2.32,7.0
1,BUTTER,"BUTTER,WHIPPED,WITH SALT",1002,0,2.11,158,0,0.06,219,19,...,26,827,0.05,2499,684,0.13,0.003,0.0,2.32,7.0
2,BUTTER OIL,"BUTTER OIL,ANHYDROUS",1003,0,0.00,193,0,0.00,256,22,...,5,2,0.01,3069,840,0.01,0.001,0.0,2.80,8.6
3,CHEESE,"CHEESE,BLUE",1004,0,5.11,74,0,2.34,75,15,...,256,1395,2.66,763,198,1.22,0.166,0.0,0.25,2.4
4,CHEESE,"CHEESE,BRICK",1005,0,3.18,76,0,2.79,94,15,...,136,560,2.60,1080,292,1.26,0.065,0.0,0.26,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7408,FROG LEGS,"FROG LEGS,RAW",80200,0,1.40,0,0,0.00,50,65,...,285,58,1.00,50,15,0.40,0.120,0.0,1.00,0.1
7409,MACKEREL,"MACKEREL,SALTED",83110,0,13.40,0,0,0.00,95,95,...,520,4450,1.10,157,47,12.00,0.410,0.0,2.38,7.8
7410,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",90240,0,3.06,0,0,0.00,53,81,...,476,265,3.00,100,30,1.30,0.100,0.0,1.50,0.2
7411,SNAIL,"SNAIL,RAW",90560,0,1.30,0,0,2.00,50,65,...,382,70,1.00,100,30,0.50,0.130,0.0,5.00,0.1
7412,TURTLE,"TURTLE,GREEN,RAW",93600,0,1.20,0,0,0.00,50,65,...,230,68,1.00,100,30,1.00,0.120,0.0,0.50,0.1

In [538]:
oFood.drop("AlphaCarotene",axis=1,inplace=True)

In [539]:
oFood.drop(["Ash","NutrientDataBankNumber","BetaCarotene","BetaCryptoxanthin"],axis=1,inplace=True)

In [540]:
oFood.drop(["Choline","LuteinandZeaxanthin","Lycopene","Manganese"],axis=1,inplace=True)

In [541]:
oFood.drop(["PantothenicAcid","Niacin","Potassium","Sodium"],axis=1,inplace=True)

In [542]:
oFood.drop(["Retinol","Phosphorus","Magnesium","Zinc"],axis=1,inplace=True)

In [543]:
oFood.drop(["Riboflavin","Selenium","Calcium","Copper"],axis=1,inplace=True)

In [544]:
oFood.drop(["Thiamin","Iron","TotalLipid"],axis=1,inplace=True)

In [545]:
oFood.drop(["HouseholdWeights.2ndHouseholdWeightDescription","HouseholdWeights.1stHouseholdWeightDescription","Water"],axis=1,inplace=True)

In [546]:
oFood

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,MonosaturatedFat,...,SaturatedFat,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,VitaminA-IU,VitaminA-RAE,VitaminB12,VitaminB6,VitaminC,VitaminE,VitaminK
0,BUTTER,"BUTTER,WITH SALT",0.06,215,0.0,717,0.85,0,0.06,21.021,...,51.368,227.00,14,2499,684,0.17,0.003,0.0,2.32,7.0
1,BUTTER,"BUTTER,WHIPPED,WITH SALT",0.06,219,0.0,717,0.85,0,0.06,23.426,...,50.489,151.00,9,2499,684,0.13,0.003,0.0,2.32,7.0
2,BUTTER OIL,"BUTTER OIL,ANHYDROUS",0.00,256,0.0,876,0.28,0,0.00,28.732,...,61.924,205.00,13,3069,840,0.01,0.001,0.0,2.80,8.6
3,CHEESE,"CHEESE,BLUE",2.34,75,0.0,353,21.40,0,0.50,7.778,...,18.669,28.35,17,763,198,1.22,0.166,0.0,0.25,2.4
4,CHEESE,"CHEESE,BRICK",2.79,94,0.0,371,23.24,0,0.51,8.598,...,18.764,132.00,113,1080,292,1.26,0.065,0.0,0.26,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7408,FROG LEGS,"FROG LEGS,RAW",0.00,50,0.0,73,16.40,0,0.00,0.053,...,0.076,0.00,0,50,15,0.40,0.120,0.0,1.00,0.1
7409,MACKEREL,"MACKEREL,SALTED",0.00,95,0.0,305,18.50,0,0.00,8.320,...,7.148,136.00,0,157,47,12.00,0.410,0.0,2.38,7.8
7410,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",0.00,53,0.0,112,23.20,0,0.00,0.068,...,0.146,0.00,0,100,30,1.30,0.100,0.0,1.50,0.2
7411,SNAIL,"SNAIL,RAW",2.00,50,0.0,90,16.10,0,0.00,0.259,...,0.361,0.00,0,100,30,0.50,0.130,0.0,5.00,0.1
7412,TURTLE,"TURTLE,GREEN,RAW",0.00,50,0.0,89,19.80,0,0.00,0.088,...,0.127,0.00,0,100,30,1.00,0.120,0.0,0.50,0.1

In [547]:
oFood.drop(["VitaminA-IU","VitaminA-RAE","VitaminB12","VitaminB6","VitaminC","VitaminE","VitaminK"],axis=1,inplace=True)

In [548]:
oFood["fat"]=oFood["PolysaturatedFat"]+oFood["MonosaturatedFat"]+oFood["SaturatedFat"]

In [549]:
oFood.drop(["MonosaturatedFat","PolysaturatedFat","SaturatedFat"],axis=1,inplace=True)

In [550]:
oFood[oFood["Category"]=="BUTTER"]=oFood[oFood["Category"]=="BUTTER"].drop([0,1,648,649])
oFood.dropna(inplace=True)

In [551]:
oFood[oFood["Category"]=="BUTTER"]

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
133,BUTTER,"BUTTER,WITHOUT SALT",0.06,215.0,0.0,717.0,0.85,0.0,0.06,227.0,14.0,75.432

In [552]:
oFood

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
2,BUTTER OIL,"BUTTER OIL,ANHYDROUS",0.00,256.0,0.0,876.0,0.28,0.0,0.00,205.00,13.0,94.350
3,CHEESE,"CHEESE,BLUE",2.34,75.0,0.0,353.0,21.40,0.0,0.50,28.35,17.0,27.247
4,CHEESE,"CHEESE,BRICK",2.79,94.0,0.0,371.0,23.24,0.0,0.51,132.00,113.0,28.146
5,CHEESE,"CHEESE,BRIE",0.45,100.0,0.0,334.0,20.75,0.0,0.45,240.00,144.0,26.249
6,CHEESE,"CHEESE,CAMEMBERT",0.46,72.0,0.0,300.0,19.80,0.0,0.46,246.00,28.0,23.006
...,...,...,...,...,...,...,...,...,...,...,...,...
7408,FROG LEGS,"FROG LEGS,RAW",0.00,50.0,0.0,73.0,16.40,0.0,0.00,0.00,0.0,0.231
7409,MACKEREL,"MACKEREL,SALTED",0.00,95.0,0.0,305.0,18.50,0.0,0.00,136.00,0.0,21.678
7410,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",0.00,53.0,0.0,112.0,23.20,0.0,0.00,0.00,0.0,0.695
7411,SNAIL,"SNAIL,RAW",2.00,50.0,0.0,90.0,16.10,0.0,0.00,0.00,0.0,0.872
7412,TURTLE,"TURTLE,GREEN,RAW",0.00,50.0,0.0,89.0,19.80,0.0,0.00,0.00,0.0,0.385

In [553]:
indexes=np.array(oFood[oFood["Category"].str.contains(r"BUTTER").fillna(False)].index)
indexes=np.delete(indexes,1,0)   
oFood[oFood["Category"].str.contains(r"BUTTER").fillna(False)]=oFood[oFood["Category"].str.contains(r"BUTTER").fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(r"BUTTER").fillna(False)]

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
133,BUTTER,"BUTTER,WITHOUT SALT",0.06,215.0,0.0,717.0,0.85,0.0,0.06,227.0,14.0,75.432

In [554]:
oFood.dropna(inplace=True)

In [555]:
oFood

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
3,CHEESE,"CHEESE,BLUE",2.34,75.0,0.0,353.0,21.40,0.0,0.50,28.35,17.0,27.247
4,CHEESE,"CHEESE,BRICK",2.79,94.0,0.0,371.0,23.24,0.0,0.51,132.00,113.0,28.146
5,CHEESE,"CHEESE,BRIE",0.45,100.0,0.0,334.0,20.75,0.0,0.45,240.00,144.0,26.249
6,CHEESE,"CHEESE,CAMEMBERT",0.46,72.0,0.0,300.0,19.80,0.0,0.46,246.00,28.0,23.006
7,CHEESE,"CHEESE,CARAWAY",3.06,93.0,0.0,376.0,25.18,0.0,0.00,28.35,0.0,27.689
...,...,...,...,...,...,...,...,...,...,...,...,...
7408,FROG LEGS,"FROG LEGS,RAW",0.00,50.0,0.0,73.0,16.40,0.0,0.00,0.00,0.0,0.231
7409,MACKEREL,"MACKEREL,SALTED",0.00,95.0,0.0,305.0,18.50,0.0,0.00,136.00,0.0,21.678
7410,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",0.00,53.0,0.0,112.0,23.20,0.0,0.00,0.00,0.0,0.695
7411,SNAIL,"SNAIL,RAW",2.00,50.0,0.0,90.0,16.10,0.0,0.00,0.00,0.0,0.872
7412,TURTLE,"TURTLE,GREEN,RAW",0.00,50.0,0.0,89.0,19.80,0.0,0.00,0.00,0.0,0.385

In [556]:
indexes=np.array(oFood[oFood["Category"].str.contains(r"CHEESE").fillna(False)].index)
indexes=np.delete(indexes,5,0)
oFood[oFood["Category"].str.contains(r"CHEESE").fillna(False)]=oFood[oFood["Category"].str.contains(r"CHEESE").fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(r"CHEESE").fillna(False)]
oFood.dropna(inplace=True)

In [557]:
remove=r"CREAM"
delIndex=49
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [558]:

remove=r"MILK"
delIndex=31
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [559]:

remove=r"No Category"
#delIndex=31
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
#indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [560]:

remove=r"DESSERT"
#delIndex=31
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
#indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [561]:

remove=r"YOGURT"
delIndex=0
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [562]:

remove=r"WHEY"
delIndex=0
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
#indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [563]:
oFood[oFood["Category"].str.contains("EGG").fillna(False)]

remove=r"EGG"
delIndex=[0,1,2]
indexes=np.array(oFood[oFood["Category"].str.contains(remove).fillna(False)].index)
indexes=np.delete(indexes,delIndex,0)
oFood[oFood["Category"].str.contains(remove).fillna(False)]=oFood[oFood["Category"].str.contains(remove).fillna(False)].drop(indexes)
oFood[oFood["Category"].str.contains(remove).fillna(False)]
oFood.dropna(inplace=True)

In [564]:
oFood[oFood["Category"].str.contains("EGG").fillna(False)]

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
111,EGG,"EGG,WHOLE,RAW,FRESH",0.77,423.0,0.0,143.0,12.58,12.0,0.77,243.0,56.0,8.273
112,EGG,"EGG,WHITE,RAW,FRESH",0.73,0.0,0.0,48.0,10.90,0.0,0.71,243.0,33.0,0.000
113,EGG,"EGG,YOLK,RAW,FRSH",3.59,1234.0,0.0,317.0,15.86,0.0,0.56,243.0,17.0,25.493

In [569]:
oFood.to_csv("saveState.csv",index=False)

In [570]:
newFile=pd.read_csv("saveState.csv")

In [571]:
newFile

,Category,Description,Carbohydrate,Cholesterol,Fiber,Kilocalories,Protein,RefusePercentage,SugarTotal,HouseholdWeights.1stHouseholdWeight,HouseholdWeights.2ndHouseholdWeight,fat
0,CHEESE,"CHEESE,CHEDDAR",1.28,105.0,0.0,403.0,24.90,0.0,0.52,132.0,244.0,31.425
1,SOUR DRSNG,"SOUR DRSNG,NON-BUTTERFAT,CULTURED,FILLED CREAM...",4.68,5.0,0.0,178.0,3.25,0.0,4.68,235.0,12.0,15.698
2,SOUR CRM,"SOUR CRM,IMITN,CULTURED",6.63,0.0,0.0,208.0,2.40,0.0,6.63,230.0,28.0,18.435
3,MILK,"MILK,INDIAN BUFFALO,FLUID",5.18,19.0,0.0,97.0,3.75,0.0,0.00,244.0,976.0,6.530
4,YOGURT,"YOGURT,PLN,WHL MILK,8 GRAMS PROT PER 8 OZ",4.66,13.0,0.0,61.0,3.47,0.0,4.66,245.0,227.0,3.081
...,...,...,...,...,...,...,...,...,...,...,...,...
6887,FROG LEGS,"FROG LEGS,RAW",0.00,50.0,0.0,73.0,16.40,0.0,0.00,0.0,0.0,0.231
6888,MACKEREL,"MACKEREL,SALTED",0.00,95.0,0.0,305.0,18.50,0.0,0.00,136.0,0.0,21.678
6889,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",0.00,53.0,0.0,112.0,23.20,0.0,0.00,0.0,0.0,0.695
6890,SNAIL,"SNAIL,RAW",2.00,50.0,0.0,90.0,16.10,0.0,0.00,0.0,0.0,0.872
6891,TURTLE,"TURTLE,GREEN,RAW",0.00,50.0,0.0,89.0,19.80,0.0,0.00,0.0,0.0,0.385